name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - pinned
        - stable
        - beta
        - stable-linux
        include:
        - build: pinned
          os: windows-2019
          rust: 1.34.0
        - build: stable
          os: windows-2019
          rust: stable
        - build: beta
          os: windows-2019
          rust: beta
        - build: stable-linux
          os: ubuntu-18.04
          rust: stable
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - run: cargo build --verbose
    - run: cargo doc --verbose
    - run: cargo test --verbose
      
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check formatting
      run: cargo fmt --all -- --check
